import type {
  CompetitorBrand,
  HeatCell,
  IntelligenceSignal,
  MacroTrigger,
  NewsSource,
  Opportunity,
  ProvinceIntel,
  RetailerRecord,
  Threat,
} from "../types";
import { scoreOpportunity } from "../scoring";

const DEMO = true as const;

export const LAST_SCAN_AT = "2026-09-01T08:42:00+02:00";

export const NEWS_SOURCES: NewsSource[] = [
  { id: "fin24", name: "Fin24", url: "https://www.news24.com/fin24", region: "South Africa", active: true },
  { id: "businesstech", name: "BusinessTech", url: "https://businesstech.co.za", region: "South Africa", active: true },
  { id: "moneyweb", name: "Moneyweb", url: "https://www.moneyweb.co.za", region: "South Africa", active: true },
  { id: "retailbrief", name: "Retail Brief Africa", url: "https://www.retailbriefafrica.co.za", region: "Africa", active: true },
  { id: "supermarket", name: "Supermarket & Retailer", url: "https://www.supermarket.co.za", region: "South Africa", active: true },
  { id: "news24", name: "News24 Business", url: "https://www.news24.com", region: "South Africa", active: true },
  { id: "citizen", name: "The Citizen", url: "https://www.citizen.co.za", region: "South Africa", active: true },
  { id: "iol", name: "IOL", url: "https://www.iol.co.za", region: "South Africa", active: true },
  { id: "timeslive", name: "TimesLIVE", url: "https://www.timeslive.co.za", region: "South Africa", active: true },
];

export const SIGNALS: IntelligenceSignal[] = [
  {
    id: "sig-maq-promo",
    title: "MAQ maintains aggressive value positioning",
    source: "BusinessTech",
    sourceUrl: "https://businesstech.co.za",
    publishedAt: "2026-09-01T07:10:00+02:00",
    detectedAt: "2026-09-01T08:42:00+02:00",
    signalType: "promotion",
    category: "Laundry Detergent",
    brand: "MAQ",
    retailer: null,
    province: null,
    summary:
      "MAQ is maintaining aggressive promotional pricing across major retail channels.",
    fact: "Demo scan: MAQ promotional pricing remains featured across major grocery banners in the latest retailer circulars.",
    interpretation:
      "This strengthens MAQ's value proposition while households face affordability pressure, increasing down-trading risk against OMO and Surf.",
    recommendation:
      "Compare OMO, Surf and MAQ share, volume and promotional intensity over the latest 12 weeks by retailer and province.",
    whyItMatters:
      "This may increase down-trading pressure against OMO and Surf among price-sensitive households.",
    suggestedInternalQuery:
      "Compare OMO, Surf and MAQ share and volume growth over the latest 12 weeks by retailer and province.",
    severity: "high",
    confidence: "high",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-shoprite-pl",
    title: "Shoprite private-label detergent ranging expands",
    source: "Retail Brief Africa",
    sourceUrl: "https://www.retailbriefafrica.co.za",
    publishedAt: "2026-08-28T09:00:00+02:00",
    detectedAt: "2026-08-28T11:20:00+02:00",
    signalType: "retailer",
    category: "Laundry Detergent",
    brand: null,
    retailer: "Shoprite",
    province: "gauteng",
    summary:
      "Shoprite is expanding house-brand laundry detergent facings in selected Gauteng stores.",
    fact: "Demo scan: Shoprite private-label detergent ranging is expanding in selected Gauteng stores.",
    interpretation:
      "Private-label growth in the value banner typically pressures mid-tier Unilever detergents first, especially Surf.",
    recommendation:
      "Check Surf and OMO facings, price gaps versus Shoprite private label, and volume share in Shoprite Gauteng over 12 weeks.",
    whyItMatters:
      "House brands in Shoprite can reset the value reference price for the aisle and pull volume from branded detergents.",
    suggestedInternalQuery:
      "Shoprite Gauteng: Surf and OMO value share, average selling price gap versus private label, and distribution of core SKUs, last 12 weeks.",
    severity: "high",
    confidence: "medium",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-fuel",
    title: "Fuel price increase tightens household cash",
    source: "Fin24",
    sourceUrl: "https://www.news24.com/fin24",
    publishedAt: "2026-08-27T06:30:00+02:00",
    detectedAt: "2026-08-27T08:15:00+02:00",
    signalType: "macro",
    category: null,
    brand: null,
    retailer: null,
    province: null,
    summary:
      "A further petrol and diesel adjustment reduces discretionary spend in lower- and middle-income households.",
    fact: "Demo scan: South African fuel prices increased at the latest monthly adjustment.",
    interpretation:
      "Higher commuting costs typically shift Home Care baskets toward smaller packs, bars, and promoted value brands.",
    recommendation:
      "Review pack-size mix and value-brand share for laundry detergents and dishwashing in the weeks following the fuel adjustment.",
    whyItMatters:
      "Fuel is a leading household cash-flow trigger for Home Care down-trading in South Africa.",
    suggestedInternalQuery:
      "Laundry and dishwashing: pack-size mix, value-tier share and volume after the latest fuel-price change versus the prior 8 weeks.",
    severity: "medium",
    confidence: "high",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-gauteng-water",
    title: "Gauteng water interruptions disrupt household routines",
    source: "News24 Business",
    sourceUrl: "https://www.news24.com",
    publishedAt: "2026-08-30T16:40:00+02:00",
    detectedAt: "2026-08-31T08:05:00+02:00",
    signalType: "macro",
    category: "Hard Surface Cleaners",
    brand: "Handy Andy",
    retailer: null,
    province: "gauteng",
    summary:
      "Municipal water interruptions in parts of Gauteng are interrupting laundry and cleaning routines.",
    fact: "Demo scan: Water supply interruptions were reported across several Gauteng municipalities in late August.",
    interpretation:
      "Water stress can delay laundry cycles and lift demand for concentrated cleaners, sanitising products and smaller wash loads once supply returns.",
    recommendation:
      "Inspect Gauteng weekly volume for laundry detergents, toilet cleaners and hard-surface cleaners around outage dates.",
    whyItMatters:
      "Unilever Home Care volume in Gauteng is sensitive to water availability; outages also create a hygiene communication window.",
    suggestedInternalQuery:
      "Gauteng weekly volume for OMO, Sunlight, Domestos and Handy Andy versus the rest of South Africa over the outage window.",
    severity: "high",
    confidence: "high",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-harpic",
    title: "Harpic steps up toilet-care visibility in Clicks",
    source: "Supermarket & Retailer",
    sourceUrl: "https://www.supermarket.co.za",
    publishedAt: "2026-08-25T10:00:00+02:00",
    detectedAt: "2026-08-25T12:40:00+02:00",
    signalType: "competitor",
    category: "Toilet Cleaners",
    brand: "Harpic",
    retailer: "Clicks",
    province: "western-cape",
    summary:
      "Harpic has increased secondary displays and promotional support in Clicks Western Cape.",
    fact: "Demo scan: Harpic secondary displays and promotional support increased in Clicks Western Cape.",
    interpretation:
      "Clicks is a high-equity hygiene destination; Harpic visibility there can take trips from Domestos among urban shoppers.",
    recommendation:
      "Compare Domestos versus Harpic value share, rate of sale and promo intensity in Clicks and Dis-Chem for 12 weeks.",
    whyItMatters:
      "Pharmacy and health banners disproportionately influence toilet-cleaner brand choice among higher-income households.",
    suggestedInternalQuery:
      "Domestos vs Harpic in Clicks and Dis-Chem: value share, volume, ASP and % sales on promo, last 12 weeks.",
    severity: "medium",
    confidence: "medium",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-boxer",
    title: "Boxer continues store expansion in KwaZulu-Natal",
    source: "Moneyweb",
    sourceUrl: "https://www.moneyweb.co.za",
    publishedAt: "2026-08-22T08:20:00+02:00",
    detectedAt: "2026-08-22T09:50:00+02:00",
    signalType: "retailer",
    category: "Laundry Bars",
    brand: "Sunlight",
    retailer: "Boxer",
    province: "kwazulu-natal",
    summary:
      "Boxer is adding stores in KwaZulu-Natal, expanding the value grocery footprint where laundry bars over-index.",
    fact: "Demo scan: Boxer announced further KwaZulu-Natal store openings in the current expansion wave.",
    interpretation:
      "New Boxer stores reset distribution for laundry bars and value detergents; Sunlight bar must be listed day one or lose the trip to Britelite and Rave.",
    recommendation:
      "Audit Sunlight bar, OMO and Surf distribution in new Boxer KZN stores versus Britelite and MAQ.",
    whyItMatters:
      "Boxer is a growth banner for lower-income Home Care missions; listing gaps become share gaps quickly.",
    suggestedInternalQuery:
      "Boxer KZN: numeric distribution and volume share for Sunlight bar, Britelite, Rave, OMO and MAQ, latest period versus year ago.",
    severity: "medium",
    confidence: "high",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-sassa",
    title: "SASSA payment dates concentrate value-channel demand",
    source: "The Citizen",
    sourceUrl: "https://www.citizen.co.za",
    publishedAt: "2026-08-20T07:00:00+02:00",
    detectedAt: "2026-08-20T08:30:00+02:00",
    signalType: "macro",
    category: null,
    brand: null,
    retailer: "Usave",
    province: null,
    summary:
      "The next SASSA payment window will concentrate grocery spend into value banners over a few days.",
    fact: "Demo scan: SASSA grant payment dates for the coming month are published and cluster household spend.",
    interpretation:
      "Home Care promotions timed to grant week in Usave, Boxer and Shoprite typically capture a disproportionate share of monthly volume.",
    recommendation:
      "Align OMO, Surf and Sunlight bar promotions with SASSA week in value banners and measure uplift versus non-grant weeks.",
    whyItMatters:
      "Grant-week timing is one of the most reliable volume levers in South African value Home Care.",
    suggestedInternalQuery:
      "Value banners: weekly volume for OMO, Surf, Sunlight bar and MAQ during SASSA payment weeks versus adjacent weeks.",
    severity: "medium",
    confidence: "high",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-clicks-reset",
    title: "Clicks Home Care aisle reset favours premium hygiene",
    source: "IOL",
    sourceUrl: "https://www.iol.co.za",
    publishedAt: "2026-08-18T11:15:00+02:00",
    detectedAt: "2026-08-18T13:00:00+02:00",
    signalType: "retailer",
    category: "Toilet Cleaners",
    brand: "Domestos",
    retailer: "Clicks",
    province: "western-cape",
    summary:
      "Clicks is resetting Home Care to emphasise premium hygiene and specialist cleaners.",
    fact: "Demo scan: Clicks Home Care planograms in selected Western Cape stores emphasise premium hygiene over grocery-equivalent SKUs.",
    interpretation:
      "Domestos can gain if the reset awards specialist hygiene blocking; it can lose if Harpic or private label take the eye-level bay.",
    recommendation:
      "Review Clicks facings and rate of sale for Domestos versus Harpic and Toilet Duck after the reset.",
    whyItMatters:
      "Planogram resets in Clicks are infrequent and lock in share of shelf for a full season.",
    suggestedInternalQuery:
      "Clicks: Domestos / Harpic / Toilet Duck facings proxy (store count × SKU count) and rate of sale, 8 weeks pre/post reset.",
    severity: "medium",
    confidence: "medium",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-stasoft",
    title: "Sta-soft promotional depth undercuts Comfort in SPAR",
    source: "TimesLIVE",
    sourceUrl: "https://www.timeslive.co.za",
    publishedAt: "2026-08-24T09:30:00+02:00",
    detectedAt: "2026-08-24T10:45:00+02:00",
    signalType: "promotion",
    category: "Fabric Conditioners",
    brand: "Sta-soft",
    retailer: "SPAR",
    province: "gauteng",
    summary:
      "Sta-soft is running deep multi-buy promotions in SPAR Gauteng against Comfort.",
    fact: "Demo scan: Sta-soft multi-buys are featured in SPAR Gauteng leaflets at a deeper discount than Comfort.",
    interpretation:
      "If Comfort does not match visibility, conditioner shoppers in SPAR will switch for the event even if they return later — the volume hole still hits the period.",
    recommendation:
      "Measure Comfort versus Sta-soft promo intensity, volume and ASP in SPAR over the promo window.",
    whyItMatters:
      "Fabric conditioner is promo-elastic in SPAR; losing the feature week is hard to recover in the same month.",
    suggestedInternalQuery:
      "SPAR Gauteng: Comfort vs Sta-soft % sales on promo, volume, ASP, last 8 weeks.",
    severity: "medium",
    confidence: "medium",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-britelite",
    title: "Britelite cuts laundry-bar price in Usave",
    source: "Retail Brief Africa",
    sourceUrl: "https://www.retailbriefafrica.co.za",
    publishedAt: "2026-08-26T08:00:00+02:00",
    detectedAt: "2026-08-26T09:10:00+02:00",
    signalType: "competitor",
    category: "Laundry Bars",
    brand: "Britelite",
    retailer: "Usave",
    province: "eastern-cape",
    summary:
      "Britelite has reduced shelf price on core laundry bars in Usave Eastern Cape.",
    fact: "Demo scan: Britelite core laundry-bar shelf price was reduced in Usave Eastern Cape.",
    interpretation:
      "Sunlight bar's price architecture in Usave is now more exposed; Eastern Cape bar shoppers are highly price-sensitive.",
    recommendation:
      "Check Sunlight bar versus Britelite and Rave price gaps, volume and distribution in Usave Eastern Cape and national value banners.",
    whyItMatters:
      "Laundry bars remain a high-penetration Unilever franchise among lower-income households; a price gap here is a share gap.",
    suggestedInternalQuery:
      "Usave: Sunlight bar vs Britelite vs Rave ASP, volume share and distribution, Eastern Cape versus national, last 12 weeks.",
    severity: "high",
    confidence: "medium",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-loadshedding",
    title: "Load-shedding Stage 2 returns in several metros",
    source: "Fin24",
    sourceUrl: "https://www.news24.com/fin24",
    publishedAt: "2026-08-29T18:00:00+02:00",
    detectedAt: "2026-08-30T07:20:00+02:00",
    signalType: "macro",
    category: null,
    brand: null,
    retailer: null,
    province: "western-cape",
    summary:
      "Stage 2 load-shedding has returned in several metros, disrupting retail hours and cold-chain adjacent missions.",
    fact: "Demo scan: Stage 2 load-shedding was reinstated across several metros in late August.",
    interpretation:
      "Outages shorten evening grocery trips and can shift Home Care purchases into daytime value banners; in-store activation windows also shrink.",
    recommendation:
      "Compare Western Cape and Gauteng daily/weekly Home Care volume around load-shedding days versus stable days.",
    whyItMatters:
      "Load-shedding changes when and where Home Care is bought, not only how much.",
    suggestedInternalQuery:
      "Weekly Home Care volume in Western Cape and Gauteng on load-shedding days versus non-outage days, last 8 weeks.",
    severity: "medium",
    confidence: "high",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-usave-maq",
    title: "Usave features MAQ on end-cap for grant week",
    source: "Supermarket & Retailer",
    sourceUrl: "https://www.supermarket.co.za",
    publishedAt: "2026-08-31T08:45:00+02:00",
    detectedAt: "2026-08-31T10:00:00+02:00",
    signalType: "retailer",
    category: "Laundry Detergent",
    brand: "MAQ",
    retailer: "Usave",
    province: "limpopo",
    summary:
      "Usave has given MAQ an end-cap feature timed to the SASSA payment window in Limpopo.",
    fact: "Demo scan: MAQ holds a Usave Limpopo end-cap during the SASSA payment window.",
    interpretation:
      "Combining a value brand, a value banner, and grant-week cash is a high-conversion stack against OMO and Surf.",
    recommendation:
      "Inspect OMO and Surf volume and share in Usave Limpopo during the feature versus the prior four weeks.",
    whyItMatters:
      "This is a concrete, localised competitive strike, not just a national price story.",
    suggestedInternalQuery:
      "Usave Limpopo: OMO, Surf, MAQ volume and value share in the feature week versus prior 4 weeks.",
    severity: "high",
    confidence: "medium",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-ariel",
    title: "Ariel concentrated format visibility increases in Game",
    source: "BusinessTech",
    sourceUrl: "https://businesstech.co.za",
    publishedAt: "2026-08-16T12:00:00+02:00",
    detectedAt: "2026-08-16T14:20:00+02:00",
    signalType: "competitor",
    category: "Laundry Detergent",
    brand: "Ariel",
    retailer: "Game",
    province: "gauteng",
    summary:
      "Ariel concentrated SKUs have gained display in Game Gauteng.",
    fact: "Demo scan: Ariel concentrated formats gained additional display in Game Gauteng.",
    interpretation:
      "Ariel remains a premium/mid threat rather than a value threat; risk is to Skip and OMO Auto in LSM 7–10, not to bars.",
    recommendation:
      "Track Skip and OMO Auto share and ASP in Game versus Ariel over 12 weeks. Confidence on a national threat is still low.",
    whyItMatters:
      "A Game display is a signal, not yet a market shift — do not over-react without share evidence.",
    suggestedInternalQuery:
      "Game: Ariel vs OMO Auto vs Skip value share, volume and ASP, last 12 weeks versus year ago.",
    severity: "low",
    confidence: "low",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
  {
    id: "sig-food-inflation",
    title: "Food inflation keeps Home Care under affordability pressure",
    source: "Fin24",
    sourceUrl: "https://www.news24.com/fin24",
    publishedAt: "2026-08-21T07:40:00+02:00",
    detectedAt: "2026-08-21T08:55:00+02:00",
    signalType: "consumer",
    category: null,
    brand: null,
    retailer: null,
    province: null,
    summary:
      "Food inflation remains elevated, leaving less room in the basket for branded Home Care.",
    fact: "Demo scan: Published food-inflation prints remain elevated relative to headline CPI.",
    interpretation:
      "When food takes a larger share of the basket, Home Care shoppers trade pack size, brand, or both — MAQ and laundry bars benefit first.",
    recommendation:
      "Split Home Care volume into value / mid / premium tiers and watch 12-week mix versus food-inflation prints.",
    whyItMatters:
      "Affordability is the macro backdrop behind almost every competitor value move this period.",
    suggestedInternalQuery:
      "National Home Care: value-tier versus mid-tier volume mix, last 12 weeks versus prior 12, overlay food inflation.",
    severity: "high",
    confidence: "high",
    commercialImpact: "unvalidated",
    demo: DEMO,
  },
];

const maqSignals = SIGNALS.filter((s) =>
  ["sig-maq-promo", "sig-usave-maq", "sig-fuel", "sig-food-inflation"].includes(s.id),
);
const barSignals = SIGNALS.filter((s) =>
  ["sig-britelite", "sig-boxer", "sig-sassa"].includes(s.id),
);
const toiletSignals = SIGNALS.filter((s) =>
  ["sig-harpic", "sig-clicks-reset"].includes(s.id),
);
const waterSignals = SIGNALS.filter((s) =>
  ["sig-gauteng-water"].includes(s.id),
);
const conditionerSignals = SIGNALS.filter((s) =>
  ["sig-stasoft"].includes(s.id),
);

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-omo-maq",
    title: "Defend OMO against MAQ",
    description:
      "MAQ is gaining competitive momentum in a high-affordability-pressure environment. Investigate OMO defence strategy.",
    category: "Laundry Detergent",
    brand: "OMO",
    opportunityScore: scoreOpportunity({
      signals: maqSignals,
      relevance: 1,
      urgency: 0.95,
      competitiveIntensity: 0.95,
      confidence: "high",
    }),
    impact: "high",
    confidence: "high",
    evidence: [
      "MAQ price and promotional pressure across major banners",
      "Usave Limpopo end-cap timed to SASSA week",
      "Fuel and food inflation tightening household cash",
      "OMO share movement still requires internal validation",
    ],
    recommendedAction:
      "Review OMO price-pack architecture and promotion in affected retailers — starting with Usave, Shoprite and Boxer.",
    status: "open",
    signalIds: maqSignals.map((s) => s.id),
    createdAt: "2026-09-01T08:42:00+02:00",
    demo: DEMO,
  },
  {
    id: "opp-sunlight-bar",
    title: "Protect Sunlight bar in value banners",
    description:
      "Britelite price cuts and Boxer expansion in KZN create a listing and price-gap risk for Sunlight laundry bars.",
    category: "Laundry Bars",
    brand: "Sunlight",
    opportunityScore: scoreOpportunity({
      signals: barSignals,
      relevance: 0.9,
      urgency: 0.75,
      competitiveIntensity: 0.8,
      confidence: "medium",
    }),
    impact: "high",
    confidence: "medium",
    evidence: [
      "Britelite shelf-price cut in Usave Eastern Cape",
      "Boxer store expansion in KwaZulu-Natal",
      "SASSA week concentrating value-channel demand",
    ],
    recommendedAction:
      "Audit Sunlight bar distribution in new Boxer stores and close the Usave price gap versus Britelite.",
    status: "open",
    signalIds: barSignals.map((s) => s.id),
    createdAt: "2026-08-26T09:10:00+02:00",
    demo: DEMO,
  },
  {
    id: "opp-domestos",
    title: "Hold Domestos in Clicks and Dis-Chem",
    description:
      "Harpic visibility and a Clicks aisle reset threaten Domestos in the specialist hygiene channel.",
    category: "Toilet Cleaners",
    brand: "Domestos",
    opportunityScore: scoreOpportunity({
      signals: toiletSignals,
      relevance: 0.85,
      urgency: 0.7,
      competitiveIntensity: 0.7,
      confidence: "medium",
    }),
    impact: "medium",
    confidence: "medium",
    evidence: [
      "Harpic secondary displays in Clicks Western Cape",
      "Clicks Home Care aisle reset towards premium hygiene",
    ],
    recommendedAction:
      "Secure Domestos eye-level blocking in the Clicks reset and match Harpic promo intensity in pharmacy banners.",
    status: "open",
    signalIds: toiletSignals.map((s) => s.id),
    createdAt: "2026-08-25T12:40:00+02:00",
    demo: DEMO,
  },
  {
    id: "opp-handy-andy",
    title: "Hygiene window from Gauteng water disruptions",
    description:
      "Water interruptions create a short hygiene-communication and hard-surface cleaning window for Handy Andy and Domestos.",
    category: "Hard Surface Cleaners",
    brand: "Handy Andy",
    opportunityScore: scoreOpportunity({
      signals: waterSignals,
      relevance: 0.7,
      urgency: 0.8,
      competitiveIntensity: 0.35,
      confidence: "high",
    }),
    impact: "medium",
    confidence: "high",
    evidence: [
      "Gauteng municipal water interruptions in late August",
      "Household cleaning routines disrupted, then concentrated when supply returns",
    ],
    recommendedAction:
      "Time Handy Andy and Domestos visibility in Gauteng retailers to the return-of-water window; validate with weekly volume.",
    status: "open",
    signalIds: waterSignals.map((s) => s.id),
    createdAt: "2026-08-31T08:05:00+02:00",
    demo: DEMO,
  },
  {
    id: "opp-comfort",
    title: "Recover Comfort promo efficiency in SPAR",
    description:
      "Sta-soft multi-buys in SPAR Gauteng are likely stealing the feature week from Comfort.",
    category: "Fabric Conditioners",
    brand: "Comfort",
    opportunityScore: scoreOpportunity({
      signals: conditionerSignals,
      relevance: 0.65,
      urgency: 0.6,
      competitiveIntensity: 0.65,
      confidence: "medium",
    }),
    impact: "medium",
    confidence: "medium",
    evidence: [
      "Sta-soft multi-buy depth in SPAR Gauteng exceeds Comfort",
    ],
    recommendedAction:
      "Rebalance Comfort promo depth and feature slots in SPAR; do not assume a national conditioner crisis from one banner.",
    status: "open",
    signalIds: conditionerSignals.map((s) => s.id),
    createdAt: "2026-08-24T10:45:00+02:00",
    demo: DEMO,
  },
];

export const THREATS: Threat[] = [
  {
    id: "thr-maq",
    title: "MAQ value pressure",
    level: "high",
    category: "Laundry Detergent",
    brand: "MAQ",
    signals: [
      "Aggressive promotions",
      "Price advantage",
      "Increased distribution in value banners",
      "Consumer affordability pressure",
    ],
    recommendedResponse: "Analyse switching from OMO and Surf to MAQ.",
  },
  {
    id: "thr-private-label",
    title: "Shoprite private-label detergent",
    level: "high",
    category: "Laundry Detergent",
    brand: "Shoprite private label",
    signals: [
      "Expanded house-brand facings",
      "Value-banner price reference reset",
      "Pressure on Surf first",
    ],
    recommendedResponse:
      "Quantify Surf and OMO share versus Shoprite private label in Gauteng.",
  },
  {
    id: "thr-harpic",
    title: "Harpic pressure on Domestos in Clicks",
    level: "medium",
    category: "Toilet Cleaners",
    brand: "Harpic",
    signals: [
      "Secondary displays in Clicks",
      "Aisle reset towards specialist hygiene",
      "Pharmacy-channel trip risk",
    ],
    recommendedResponse:
      "Analyse Domestos versus Harpic rate of sale in Clicks and Dis-Chem.",
  },
];

export const MACRO_TRIGGERS: MacroTrigger[] = [
  {
    id: "mac-fuel",
    title: "Fuel price increase",
    type: "consumer-economy",
    location: "National",
    severity: "medium",
    startDate: "2026-08-27",
    endDate: null,
    description: "Monthly petrol and diesel adjustment at the pumps.",
    affectedConsumers: "Commuter households nationally, especially LSM 4–7",
    potentialHomecareImpact:
      "Down-trading to value detergents, laundry bars and smaller packs.",
    recommendedInternalQuery:
      "Pack-size mix and value-tier share in laundry and dishwashing after 27 Aug versus prior 8 weeks.",
  },
  {
    id: "mac-food",
    title: "Elevated food inflation",
    type: "consumer-economy",
    location: "National",
    severity: "high",
    startDate: "2026-08-21",
    endDate: null,
    description: "Food inflation remains above headline CPI.",
    affectedConsumers: "All grocery shoppers; sharpest in lower-income baskets",
    potentialHomecareImpact:
      "Home Care loses basket share; MAQ and bars gain relative to mid-tier liquids.",
    recommendedInternalQuery:
      "Home Care value-tier versus mid-tier volume mix, 12 vs prior 12 weeks.",
  },
  {
    id: "mac-sassa",
    title: "SASSA payment window",
    type: "cash-flow",
    location: "National, concentrated in value banners",
    severity: "medium",
    startDate: "2026-09-03",
    endDate: "2026-09-07",
    description: "Social-grant payments cluster grocery spend into a few days.",
    affectedConsumers: "Grant-receiving households shopping Usave, Boxer, Shoprite",
    potentialHomecareImpact:
      "Promotions timed to grant week capture outsized monthly volume.",
    recommendedInternalQuery:
      "Weekly volume in value banners during SASSA weeks versus adjacent weeks.",
  },
  {
    id: "mac-water",
    title: "Gauteng water interruptions",
    type: "infrastructure",
    location: "Gauteng",
    severity: "high",
    startDate: "2026-08-28",
    endDate: "2026-09-02",
    description: "Municipal water interruptions across several Gauteng metros.",
    affectedConsumers: "Households in affected Gauteng municipalities",
    potentialHomecareImpact:
      "Deferred laundry; concentrated cleaning and hygiene demand when water returns.",
    recommendedInternalQuery:
      "Gauteng weekly volume for OMO, Sunlight, Domestos, Handy Andy versus RSA.",
  },
  {
    id: "mac-loadshedding",
    title: "Load-shedding Stage 2",
    type: "infrastructure",
    location: "Western Cape, Gauteng metros",
    severity: "medium",
    startDate: "2026-08-29",
    endDate: null,
    description: "Stage 2 load-shedding restored in several metros.",
    affectedConsumers: "Urban households and evening grocery shoppers",
    potentialHomecareImpact:
      "Trip timing shifts; in-store activation windows shorten.",
    recommendedInternalQuery:
      "Home Care volume on load-shedding days versus stable days in WC and GP.",
  },
  {
    id: "mac-rates",
    title: "Interest rates still restrictive",
    type: "consumer-economy",
    location: "National",
    severity: "medium",
    startDate: "2026-07-31",
    endDate: null,
    description: "Repo rate remains restrictive for highly indebted households.",
    affectedConsumers: "Credit-active middle-income households",
    potentialHomecareImpact:
      "Sustained preference for promotions and larger-value multi-buys when cash is available.",
    recommendedInternalQuery:
      "Promo-driven volume share of Home Care, last 6 months versus 2024.",
  },
];

export const COMPETITORS: CompetitorBrand[] = [
  {
    id: "omo",
    name: "OMO",
    company: "Unilever",
    category: "Laundry Detergent",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "medium",
    promotionalActivity: "medium",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "medium",
    socialActivity: "medium",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Core Unilever franchise under value pressure from MAQ. Defence is the #1 commercial question this period.",
  },
  {
    id: "surf",
    name: "Surf",
    company: "Unilever",
    category: "Laundry Detergent",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "medium",
    promotionalActivity: "high",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Most exposed Unilever detergent to private-label and MAQ in value banners.",
  },
  {
    id: "skip",
    name: "Skip",
    company: "Unilever",
    category: "Laundry Detergent",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Premium auto positioning; watch Ariel in Game rather than MAQ.",
  },
  {
    id: "maq",
    name: "MAQ",
    company: "Bliss Brands",
    category: "Laundry Detergent",
    ownership: "competitor",
    active: true,
    threatLevel: "high",
    priceActivity: "high",
    promotionalActivity: "high",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "medium",
    socialActivity: "medium",
    retailerActivity: "high",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Primary competitive threat. Value positioning plus grant-week features is a coherent attack on OMO and Surf.",
  },
  {
    id: "ariel",
    name: "Ariel",
    company: "Procter & Gamble",
    category: "Laundry Detergent",
    ownership: "competitor",
    active: true,
    threatLevel: "low",
    priceActivity: "medium",
    promotionalActivity: "medium",
    newLaunches: "medium",
    distribution: "low",
    marketingActivity: "medium",
    socialActivity: "low",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Concentrated-format display in Game is a weak national signal. Do not elevate to a top threat without share evidence.",
  },
  {
    id: "sunlight-bar",
    name: "Sunlight",
    company: "Unilever",
    category: "Laundry Bars",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "medium",
    promotionalActivity: "medium",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Must stay listed and price-competitive in Boxer and Usave as Britelite pushes price.",
  },
  {
    id: "britelite",
    name: "Britelite",
    company: "Britelite",
    category: "Laundry Bars",
    ownership: "competitor",
    active: true,
    threatLevel: "high",
    priceActivity: "high",
    promotionalActivity: "medium",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Price-led attack on Sunlight bar in Usave Eastern Cape. High relevance, medium confidence until volume is seen.",
  },
  {
    id: "rave",
    name: "Rave",
    company: "Rave",
    category: "Laundry Bars",
    ownership: "competitor",
    active: true,
    threatLevel: "medium",
    priceActivity: "medium",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Secondary bar competitor. Monitor in Boxer KZN alongside Britelite.",
  },
  {
    id: "sunlight-dish",
    name: "Sunlight",
    company: "Unilever",
    category: "Dishwashing",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "medium",
    promotionalActivity: "medium",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "medium",
    socialActivity: "medium",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "No new external dishwashing threat this period. Keep watching private label and Finish in premium auto.",
  },
  {
    id: "finish",
    name: "Finish",
    company: "Reckitt",
    category: "Dishwashing",
    ownership: "competitor",
    active: true,
    threatLevel: "low",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "medium",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Auto-dishwasher niche. Limited overlap with Sunlight hand-wash franchise.",
  },
  {
    id: "domestos",
    name: "Domestos",
    company: "Unilever",
    category: "Toilet Cleaners",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "low",
    promotionalActivity: "medium",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "medium",
    socialActivity: "medium",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Defend in Clicks/Dis-Chem this period; grocery franchise looks more stable on external signals.",
  },
  {
    id: "harpic",
    name: "Harpic",
    company: "Reckitt",
    category: "Toilet Cleaners",
    ownership: "competitor",
    active: true,
    threatLevel: "medium",
    priceActivity: "medium",
    promotionalActivity: "high",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "medium",
    socialActivity: "medium",
    retailerActivity: "high",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Most active toilet-care competitor this period, concentrated in Clicks Western Cape.",
  },
  {
    id: "toilet-duck",
    name: "Toilet Duck",
    company: "SC Johnson",
    category: "Toilet Cleaners",
    ownership: "competitor",
    active: true,
    threatLevel: "low",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Present in the Clicks reset. Secondary to Harpic as a Domestos threat.",
  },
  {
    id: "jik",
    name: "Jik",
    company: "Reckitt",
    category: "Toilet Cleaners",
    ownership: "competitor",
    active: true,
    threatLevel: "low",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Bleach franchise; limited new activity in this scan window.",
  },
  {
    id: "comfort",
    name: "Comfort",
    company: "Unilever",
    category: "Fabric Conditioners",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "medium",
    promotionalActivity: "medium",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "medium",
    socialActivity: "low",
    retailerActivity: "medium",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "SPAR Gauteng promo gap versus Sta-soft is the live issue, not a national brand crisis.",
  },
  {
    id: "stasoft",
    name: "Sta-soft",
    company: "Unilever",
    category: "Fabric Conditioners",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "high",
    promotionalActivity: "high",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "high",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Unilever-owned in SA; deep SPAR multi-buys may be stealing from Comfort rather than from a competitor.",
  },
  {
    id: "handy-andy",
    name: "Handy Andy",
    company: "Unilever",
    category: "Hard Surface Cleaners",
    ownership: "unilever",
    active: true,
    threatLevel: "own",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "high",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation:
      "Gauteng water disruptions are a demand-timing opportunity more than a competitive threat.",
  },
  {
    id: "plush",
    name: "Plush",
    company: "Plush Professional",
    category: "Hard Surface Cleaners",
    ownership: "competitor",
    active: true,
    threatLevel: "low",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation: "No material new external signal in this period.",
  },
  {
    id: "mr-sheen",
    name: "Mr Sheen",
    company: "Reckitt",
    category: "Hard Surface Cleaners",
    ownership: "competitor",
    active: true,
    threatLevel: "low",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation: "Quiet this scan. Continue routine monitoring.",
  },
  {
    id: "cobra",
    name: "Cobra",
    company: "SC Johnson",
    category: "Hard Surface Cleaners",
    ownership: "competitor",
    active: true,
    threatLevel: "low",
    priceActivity: "low",
    promotionalActivity: "low",
    newLaunches: "none",
    distribution: "medium",
    marketingActivity: "low",
    socialActivity: "low",
    retailerActivity: "low",
    shareMovement: "CONNECT DATA",
    aiInterpretation: "No new floor-care signal in this window.",
  },
];

export const RETAILERS: RetailerRecord[] = [
  {
    id: "shoprite",
    name: "Shoprite",
    type: "Value grocery",
    active: true,
    currentPromotions: "Private-label detergent ranging expansion in Gauteng",
    privateLabel: "House-brand detergent facings increasing",
    priceChanges: "Value reference price in laundry aisle under review",
    competitorActivity: "MAQ well featured; Unilever mid-tier at risk",
    storeNetwork: "Stable core; intensity via ranging not new stores",
    distributionChanges: "Private-label SKUs added in selected GP stores",
    homeCareActivity: "Laundry detergent is the live battleground",
    intensity: 78,
  },
  {
    id: "checkers",
    name: "Checkers",
    type: "Mainstream grocery",
    active: true,
    currentPromotions: "Routine multi-buys; no standout Home Care event",
    privateLabel: "Limited private-label pressure versus Shoprite",
    priceChanges: "Mainstream pricing; OMO still a destination brand",
    competitorActivity: "MAQ present but less dominant than in value banners",
    storeNetwork: "Stable",
    distributionChanges: "No material listing change in this scan",
    homeCareActivity: "Watch for copy of Shoprite private-label play",
    intensity: 42,
  },
  {
    id: "usave",
    name: "Usave",
    type: "Hard discount",
    active: true,
    currentPromotions: "MAQ end-cap in Limpopo for SASSA week; Britelite bar price cut in EC",
    privateLabel: "Assortment stays tight and price-led",
    priceChanges: "Britelite bar shelf-price reduction in Eastern Cape",
    competitorActivity: "Highest competitive intensity this period",
    storeNetwork: "Growth banner in lower-income catchments",
    distributionChanges: "End-cap allocation to MAQ in Limpopo",
    homeCareActivity: "Grant-week Home Care is being conceded to value competitors",
    intensity: 91,
  },
  {
    id: "pnp",
    name: "Pick n Pay",
    type: "Mainstream grocery",
    active: true,
    currentPromotions: "Standard leaflet; no distinctive Home Care strike",
    privateLabel: "PnP branded detergent present, not expanding this scan",
    priceChanges: "No standout national cut",
    competitorActivity: "MAQ listed; intensity below Shoprite/Usave",
    storeNetwork: "Restructuring continues; treat store-level data with care",
    distributionChanges: "No confirmed Home Care delist in this demo scan",
    homeCareActivity: "Secondary watch, not a lead story",
    intensity: 38,
  },
  {
    id: "boxer",
    name: "Boxer",
    type: "Value grocery",
    active: true,
    currentPromotions: "Expansion-led rather than promo-led this window",
    privateLabel: "Limited",
    priceChanges: "Value positioning intact",
    competitorActivity: "Laundry bars and MAQ will fight for new-store listings",
    storeNetwork: "Store expansion in KwaZulu-Natal",
    distributionChanges: "New stores = new distribution opportunities and risks",
    homeCareActivity: "Sunlight bar day-one listing is the Unilever question",
    intensity: 67,
  },
  {
    id: "spar",
    name: "SPAR",
    type: "Independent grocery",
    active: true,
    currentPromotions: "Sta-soft multi-buys in Gauteng",
    privateLabel: "Variable by independent",
    priceChanges: "Promo depth on Sta-soft ahead of Comfort",
    competitorActivity: "Conditioner battle is intra-Unilever as well as competitive",
    storeNetwork: "Stable",
    distributionChanges: "None material",
    homeCareActivity: "Fabric conditioner is the SPAR story this period",
    intensity: 55,
  },
  {
    id: "game",
    name: "Game",
    type: "General merchandise",
    active: true,
    currentPromotions: "Ariel concentrated formats on display in Gauteng",
    privateLabel: "Not material in Home Care",
    priceChanges: "Pack-price architecture on concentrated detergents",
    competitorActivity: "Ariel visibility up; national threat still low confidence",
    storeNetwork: "Stable",
    distributionChanges: "Display, not listing, is the change",
    homeCareActivity: "Premium/mid laundry only",
    intensity: 33,
  },
  {
    id: "clicks",
    name: "Clicks",
    type: "Health & beauty",
    active: true,
    currentPromotions: "Harpic secondary displays; aisle reset in Western Cape",
    privateLabel: "Clicks-branded hygiene present",
    priceChanges: "Premium hygiene price points holding",
    competitorActivity: "Harpic most active",
    storeNetwork: "Stable",
    distributionChanges: "Home Care planogram reset",
    homeCareActivity: "Toilet care and specialist hygiene",
    intensity: 62,
  },
  {
    id: "dischem",
    name: "Dis-Chem",
    type: "Health & beauty",
    active: true,
    currentPromotions: "No standout Home Care event in this scan",
    privateLabel: "Limited",
    priceChanges: "Stable",
    competitorActivity: "Watch for Harpic spillover from Clicks",
    storeNetwork: "Stable",
    distributionChanges: "None confirmed",
    homeCareActivity: "Toilet care follow-on from Clicks",
    intensity: 28,
  },
];

const HEAT_BRANDS = ["OMO", "Surf", "MAQ", "Sunlight bar", "Britelite", "Domestos", "Harpic", "Comfort", "Handy Andy"];
const HEAT_RETAILERS = ["Shoprite", "Checkers", "Usave", "Pick n Pay", "Boxer", "SPAR", "Game", "Clicks", "Dis-Chem"];
const HEAT_SCORES: Record<string, number> = {
  "OMO|Shoprite": 72,
  "OMO|Checkers": 48,
  "OMO|Usave": 88,
  "OMO|Pick n Pay": 40,
  "OMO|Boxer": 70,
  "OMO|SPAR": 44,
  "OMO|Game": 35,
  "OMO|Clicks": 12,
  "OMO|Dis-Chem": 8,
  "Surf|Shoprite": 80,
  "Surf|Checkers": 36,
  "Surf|Usave": 84,
  "Surf|Pick n Pay": 38,
  "Surf|Boxer": 74,
  "Surf|SPAR": 32,
  "Surf|Game": 18,
  "Surf|Clicks": 6,
  "Surf|Dis-Chem": 4,
  "MAQ|Shoprite": 82,
  "MAQ|Checkers": 50,
  "MAQ|Usave": 94,
  "MAQ|Pick n Pay": 46,
  "MAQ|Boxer": 78,
  "MAQ|SPAR": 40,
  "MAQ|Game": 22,
  "MAQ|Clicks": 10,
  "MAQ|Dis-Chem": 6,
  "Sunlight bar|Shoprite": 60,
  "Sunlight bar|Checkers": 22,
  "Sunlight bar|Usave": 86,
  "Sunlight bar|Pick n Pay": 24,
  "Sunlight bar|Boxer": 90,
  "Sunlight bar|SPAR": 28,
  "Sunlight bar|Game": 8,
  "Sunlight bar|Clicks": 4,
  "Sunlight bar|Dis-Chem": 2,
  "Britelite|Shoprite": 48,
  "Britelite|Checkers": 14,
  "Britelite|Usave": 88,
  "Britelite|Pick n Pay": 16,
  "Britelite|Boxer": 70,
  "Britelite|SPAR": 18,
  "Britelite|Game": 4,
  "Britelite|Clicks": 2,
  "Britelite|Dis-Chem": 2,
  "Domestos|Shoprite": 34,
  "Domestos|Checkers": 40,
  "Domestos|Usave": 20,
  "Domestos|Pick n Pay": 38,
  "Domestos|Boxer": 18,
  "Domestos|SPAR": 36,
  "Domestos|Game": 24,
  "Domestos|Clicks": 76,
  "Domestos|Dis-Chem": 64,
  "Harpic|Shoprite": 22,
  "Harpic|Checkers": 30,
  "Harpic|Usave": 12,
  "Harpic|Pick n Pay": 28,
  "Harpic|Boxer": 10,
  "Harpic|SPAR": 26,
  "Harpic|Game": 18,
  "Harpic|Clicks": 84,
  "Harpic|Dis-Chem": 58,
  "Comfort|Shoprite": 40,
  "Comfort|Checkers": 46,
  "Comfort|Usave": 18,
  "Comfort|Pick n Pay": 44,
  "Comfort|Boxer": 16,
  "Comfort|SPAR": 72,
  "Comfort|Game": 28,
  "Comfort|Clicks": 14,
  "Comfort|Dis-Chem": 10,
  "Handy Andy|Shoprite": 36,
  "Handy Andy|Checkers": 38,
  "Handy Andy|Usave": 22,
  "Handy Andy|Pick n Pay": 34,
  "Handy Andy|Boxer": 20,
  "Handy Andy|SPAR": 32,
  "Handy Andy|Game": 26,
  "Handy Andy|Clicks": 30,
  "Handy Andy|Dis-Chem": 24,
};

export const HEATMAP: HeatCell[] = HEAT_BRANDS.flatMap((brand) =>
  HEAT_RETAILERS.map((retailer) => ({
    brand,
    retailer,
    score: HEAT_SCORES[`${brand}|${retailer}`] ?? 20,
  })),
);

export const PROVINCES: ProvinceIntel[] = [
  {
    id: "gauteng",
    name: "Gauteng",
    signals: [
      { label: "Water disruption", severity: "high" },
      { label: "Consumer pressure", severity: "high" },
      { label: "SPAR conditioner promo", severity: "medium" },
    ],
    summary:
      "Water interruptions plus Shoprite private-label ranging and SPAR conditioner promo depth. Highest density of Home Care signals.",
  },
  {
    id: "kwazulu-natal",
    name: "KwaZulu-Natal",
    signals: [{ label: "Boxer expansion", severity: "medium" }],
    summary:
      "Boxer store expansion makes laundry-bar and value-detergent listings the provincial priority.",
  },
  {
    id: "western-cape",
    name: "Western Cape",
    signals: [
      { label: "Load-shedding", severity: "medium" },
      { label: "Clicks aisle reset", severity: "medium" },
    ],
    summary:
      "Clicks hygiene reset and Harpic displays, with load-shedding affecting trip timing.",
  },
  {
    id: "eastern-cape",
    name: "Eastern Cape",
    signals: [{ label: "Britelite price cut", severity: "high" }],
    summary: "Usave laundry-bar price cut is the sharpest provincial competitive move.",
  },
  {
    id: "free-state",
    name: "Free State",
    signals: [{ label: "Affordability backdrop", severity: "medium" }],
    summary: "No localised strike this scan. National affordability still applies.",
  },
  {
    id: "limpopo",
    name: "Limpopo",
    signals: [{ label: "MAQ Usave end-cap", severity: "high" }],
    summary: "Grant-week MAQ end-cap in Usave is a concrete local attack on OMO and Surf.",
  },
  {
    id: "mpumalanga",
    name: "Mpumalanga",
    signals: [{ label: "Affordability backdrop", severity: "medium" }],
    summary: "No distinct provincial signal above the national macro backdrop.",
  },
  {
    id: "north-west",
    name: "North West",
    signals: [{ label: "Affordability backdrop", severity: "medium" }],
    summary: "Quiet this window. Continue routine monitoring.",
  },
  {
    id: "northern-cape",
    name: "Northern Cape",
    signals: [{ label: "Quiet", severity: "low" }],
    summary: "No competitor or retailer strike detected in this scan.",
  },
];

export const SCAN_NOTIFICATIONS = [
  {
    id: "n1",
    title: "MAQ Usave end-cap detected",
    time: "Today, 08:42",
    severity: "high" as const,
  },
  {
    id: "n2",
    title: "Gauteng water interruptions added to macro",
    time: "Yesterday, 08:05",
    severity: "high" as const,
  },
  {
    id: "n3",
    title: "Weekly brief ready to generate",
    time: "Mon, 07:15",
    severity: "medium" as const,
  },
];
